use_frameworks!

platform :ios, '10.0'

target 'StyledText_Example' do
  pod 'StyledText', :path => '../'

  target 'StyledText_Tests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'Quick'
    pod 'iOSSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
