use_frameworks!

platform :ios, '10.0'

target 'StyledText_Example' do
  pod 'StyledText', :path => '../'

  target 'StyledText_Tests' do
    inherit! :search_paths
    pod 'Nimble', '~> 8.0.5'
    pod 'Quick'
    pod 'iOSSnapshotTestCase'
    pod 'Nimble-Snapshots', '~> 8.1.1'
  end
end
